####

GET http://localhost:4004/odata/v4/cirheader

####

PATCH http://localhost:4004/odata/v4/cirheader(969ebe14-ad21-43ec-be92-b51b90a30572)
Content-Type: application/json

{"cirno":"CIR-40",
"status":"Approved",
"approver":"muthu",
"approveddate":"2024-04-08",
"approvercomments":"Approved",
"ecirno":"ecirno-40"}

#####
POST http://localhost:4004/odata/v4/cirheader
Content-Type: application/json;IEEE754Compatible=true

{
  "items": [
    {
      "companycode": 567,
      "responsiblearea": "resSavarimuthu",
      "totreqcapital": 20000,
      "currency": "EUR",
      "plantcode": 1234,
      "functiontype": "functiontyp",
      "prjdesc": "prjec",
      "createddatestr": "02/04/2024",
       "closuredatestr": "02/04/2025"
    }
  ]
}

#####

POST http://localhost:4004/odata/v4/cirheader
Content-Type: application/json;IEEE754Compatible=true

{"cirno":"",
"status":"In progress",
"requestor":"",
"approver":"",
"approvercomments":"",
"ecirno":"",
"items":[{
        "functiontype":"Investments Project",
        "capbudgettype":"Local Budget",
        "prjstage":"Fully Funding",
        "prjtitle":"New Service Jaguar",
        "prjtitloclang":"",
        "prjdesc":"prjdesc",
        "costcenter":1000,
        "controlarea":1,
        "companycode":1,
        "createddatestr":"02/04/2024",
        "closuredatestr":"02/05/2024",
        "totreqcapital":8000,
        "currency":"EUR",
        "fxrate":0.0,
        "totreqcapitalusd":1,
        "plantcode":1101,
        "gbszone":"US",
        "investtype":"",
        "investnode":"",
        "responsiblearea":"Verantwortlicher A",
        "prjtype":"",
        "location":"",
        "remarks":""
}]}

####

POST http://localhost:4004/odata/v4/author
Content-Type: application/json;IEEE754Compatible=true

{"authorid":111,"authorname":"Muthu","books":[{
"bookid":12,"title":"Humane","descr":"Mankind","price":100,"stock":150
}]}

######


POST http://localhost:4004/odata/v4/cirheader
Content-Type: application/json;IEEE754Compatible=true

{
  "items":[{
    "totreqcapital":10000,
    "currency":"INR",
    "createddatestr":"12/04/2024",
    "closuredatestr":"13/04/2024"
  }]
}